### ISSUE TITLE
Font size not changing

### ISSUE THREAD

**Issue by nicknikolov** [reedes/vim-thematic#17]
Hi there!

Thanks for making this. I wanted to use this plugin to change themes when I write markdown. Most importantly I wanted to have bigger font size. I tried putting this in my .vimrc
```
let g:thematic#themes = {
\ 'dark_matter'  : {
\                },
\ 'pencil_lite' :{'colorscheme': 'pencil',
\                 'font-size': 28,
\                 'background': 'light',
\                 'ruler': 1,
\                },
\ }
```

The theme changes but font-size stays the same. I'm using MacVim on El Capitan.

Thanks

**Comment by reedes** [comment]
I'm using MacVim on El Capitan with the font-size successfully working, so something unexpected is going on.

Could you paste the result of 

```
mvim --version
```

**Comment by nicknikolov** [comment]
Sorry for not coming back to you, I will close this for now and re-open when I have time to test.
